name: Makefile CI

on:
  push:
    branches: [ "openwrt-21.02" ]
  pull_request:
    branches: [ "openwrt-21.02" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up dependencies
      run: sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang clangd cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libreadline-dev libssl-dev libtool lld lldb lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply python-docutils qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

    - name: update feeds
      run: ./scripts/feeds update -a

    - name: install feeds
      run: ./scripts/feeds install -a

    - name: copy config file
      run:  cp -f defconfig/mt7981-ax3000.config .config
      
    - name: configure
      run: make menuconfig

    - name: make
      run: make V=s -j$(nproc)

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
