name: Makefile CI

on:
  push:
    branches: [ "openwrt-21.02" ]
  pull_request:
    branches: [ "openwrt-21.02" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: copy config file
      run:  -f defconfig/mt7981-ax3000.config .config

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
