name: Makefile CI

on:
  push:
    branches: [ "openwrt-21.02" ]
  pull_request:
    branches: [ "openwrt-21.02" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up dependencies
      run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'

    - name: update feeds
      run: ./scripts/feeds update -a

    - name: install feeds
      run: ./scripts/feeds install -a

    - name: copy config file
      run:  cp -f defconfig/mt7981-ax3000.config .config
      
    - name: configure
      run: make menuconfig

    - name: make
      run: make V=s -j$(nproc)

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
