name: Makefile CI

on:
  push:
    branches: [ "openwrt-21.02" ]
  pull_request:
    branches: [ "openwrt-21.02" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache feeds
      uses: actions/cache@v3
      with:
        path: |
          ./feeds
          ./package/feeds
        key: ${{ runner.os }}-feeds-${{ hashFiles('feeds.conf') }}
        restore-keys: |
          ${{ runner.os }}-feeds-

    - name: Cache download directory
      uses: actions/cache@v3
      with:
        path: ./dl
        key: ${{ runner.os }}-dl-${{ hashFiles('feeds.conf') }}
        restore-keys: |
          ${{ runner.os }}-dl-

    - name: Cache build directory
      uses: actions/cache@v3
      with:
        path: ./build_dir
        key: ${{ runner.os }}-build-${{ hashFiles('feeds.conf') }}
        restore-keys: |
          ${{ runner.os }}-build-
          
    - name: set up dependencies
      run: curl -L https://build-scripts.immortalwrt.eu.org/init_build_environment.sh | sudo bash
      
    - name: update feeds
      run: ./scripts/feeds update -a

    - name: install feeds
      run: ./scripts/feeds install -a

    - name: copy config file
      run:  cp -f defconfig/mt7981-ax3000.config .config | make defconfig

    - name: make
      run: make V=s -j$(nproc)
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: ./bin

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v4
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v4
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin
        asset_name: firmware.bin
        asset_content_type: application/octet-stream
